serve: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
baseurl:
lunr_search:
  stopwords: "stopwords.txt"
  min_length: 3
production_url : http://username.github.com/clean-blog
permalink: :title
name: "{Young}ist"
description: "Your source for independent, youth-led political and cultural news analysis, digital storytelling, and creative intervention."
url: http://www.youngist.github.io/clean-blog
prose:
  rooturl: '_posts'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "article"
          placeholder: "Create"
          alterable: true
      - name: "maintitle"
        field:
          element: "text"
          label: "Title of piece for SEO"
          value: "- {Young}ist"
          type: "text"
      - name: "headline"
        field:
          element: "text"
          label: "Headline"
          value: "undefined"
          type: "text"
      - name: "tagline"
        field:
          element: "text"
          label: "tagline"
          value: "undefined"
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Choose Tags"
          alterable: true
      - name: "featuredphoto"
        field:
          element: "text"
          label: "Featured photo"
          value: "undefined"
          type: "text"
      - name: "featuredphotoalttext"
        field:
          element: "text"
          label: "Featured photo alt text"
          value: "undefined"
          type: "text"
      - name: "videourl"
        field:
          element: "text"
          label: "videourl"
          value: "undefined"
          type: "text"
      - name: "contributors"
        field:
          element: "multiselect"
          label: "Contributors"
          placeholder: "Create"
          alterable: true
      - name: "contributorphoto"
        field:
          element: "text"
          label: "Contributor photo"
          value: "undefined"
          type: "text"
      - name: "contributorshortbio"
        field:
          element: "text"
          label: "Contributor short bio"
          value: "undefined"
          type: "text"
      - name: "contributortwitter"
        field:
          element: "text"
          label: "Contributor twitter"
          value: "undefined"
          type: "text"
      - name: "contributorage"
        field:
          element: "text"
          label: "Contributor age"
          value: "undefined"
          type: "text"
