serve: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
baseurl: /clean-blog
production_url : http://username.github.com/
permalink: :title
name: "{young}ist"
description: "Your source for independent, youth-led political and cultural news analysis, digital storytelling, and creative intervention."
url: http://www.youngist.github.io/clean-blog
prose:
  rooturl: '_posts'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "maintitle"
        field:
          element: "text"
          label: "Title"
          value: "Title of piece"
          type: "text"
      - name: "contributors"
        field:
          element: "multiselect"
          label: "Contributors"
          placeholder: "Create or choose"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true